### ISSUE TITLE
App license

### ISSUE THREAD

**Issue by vgvassilev** [FireflyLogic/couchbase-connect-14#3]
Hi,
  Thanks for the work! I was wondering what is the license agreement for the app? Does it have MIT-like license or it is something else?
Thanks,
Vassil

**Comment by benhenderson** [comment]
Hi, Vassil. Sorry for the ambiguity. Yes, you can use this code for any purpose.

**Comment by vgvassilev** [comment]
Hi Ben, thanks for the reply. I'd feel more comfortable if there was some sort of license, say MIT. I will submit a PR with a MIT license agreement to save your time. Would that be okay?

**Comment by benhenderson** [comment]
Thanks, Vassil. I appreciate you taking time to create the pull request.
